name: Publish NuGet package

# Controls when the action will run. 
on:
  push:
    branches: 
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  publish-nuget:
    name: Build, Pack, and Publish package to NuGet
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # Projects to publish
        project: [ 
          { name: "SocialGuard Common", path: "SocialGuard.Common/SocialGuard.Common.csproj" } 
        ]
        
        # Sources to publish to
        nuget: [ 
          { name: "NuGet", source: "https://api.nuget.org", key: "${{ secrets.NUGET_TOKEN }}" }, 
          { name: "GitHub Packages", source: "https://nuget.pkg.github.com/Nodsoft", key: "${{ secrets.GITHUB_TOKEN }}" } 
        ]
        
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      # Publish
      - name: Publish ${{ matrix.project.name }} to ${{ matrix.nuget.name }}
        id: publish_nuget
        uses: Rebel028/publish-nuget@v2.7.0
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: ${{ matrix.project.path }}
          
          # NuGet package id, used for version detection & defaults to project name
          # PACKAGE_NAME: Core
          
          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          # VERSION_FILE_PATH: Directory.Build.props

          # Regex pattern to extract version info in a capturing group
          # VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          
          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          # VERSION_STATIC: 1.0.0

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: true

          # Format of the git tag, [*] gets replaced with actual version
          # TAG_FORMAT: v*

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{ matrix.nuget.key }}

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          NUGET_SOURCE: ${{ matrix.nuget.source }}

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          # INCLUDE_SYMBOLS: false
